# Maximum memory limit in RAM
maxmemory 256mb

# Least Recently Used (LRU):
# When memory reaches 256MB, Redis evicts the least recently used keys
# that have a TTL (Time To Live: the lifetime of a key, measured in seconds).
maxmemory-policy volatile-lru

# Enable RDB persistence to save data to disk

# Save after 900 seconds if at least 1 key has changed
save 900 1

# Save after 300 seconds if at least 10 keys have changed
save 300 10

# Save after 60 seconds if at least 10,000 keys have changed
save 60 10000

# Directory where Redis stores persistence files
dir /data