// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
	ListUsersUserCreatedAtAsc(ctx context.Context, arg ListUsersUserCreatedAtAscParams) ([]User, error)
	ListUsersUserCreatedAtDesc(ctx context.Context, arg ListUsersUserCreatedAtDescParams) ([]User, error)
	ListUsersUserIdAsc(ctx context.Context, arg ListUsersUserIdAscParams) ([]User, error)
	ListUsersUserIdDesc(ctx context.Context, arg ListUsersUserIdDescParams) ([]User, error)
	RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	SoftDeleteUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	TrashUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
