FROM golang:1.26.5-alpine as builder

RUN apk update && apk add --no-cache git curl

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY ../go.mod ./
COPY ../go.sum ./

RUN go mod download

COPY . .

RUN go build -o main ../cmd/api

# ======= STAGE 2: RUNTIME CONTAINER =========
FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/main .

COPY .env .

EXPOSE 8080

CMD ["./main"]