@baseUrl=http://localhost:8080

### Create new user
# @name createUserRequest
POST {{baseUrl}}/api/v1/users
Content-Type: application/json

{
    "name": "User name 1",
    "email": "abc@gmail.com"
}

### Get user by ID
GET {{baseUrl}}/api/v1/users/{{createUserRequest.response.body.data.uuid}}